### ISSUE TITLE
Fix Electron app for new backend

### ISSUE THREAD

**Issue by Liioooo** [logigator/logigator#4]
### Description

Electron Login through BrowserWindow

https://github.com/gary-archer/authguidance.desktopsample.final/tree/25a1d3952f046c016d93812d570339ed6f353026

**Comment by Liioooo** [comment]
TODO: fix issue in Electron, that profile image cannot be loaded, because of relative urls and some big CORS problems

**Comment by Liioooo** [comment]
TODO: Location should not be rewritten in electron.

**Comment by Liioooo** [comment]
TODO: Deployment with Github Actions and checking for updates

**Comment by Liioooo** [comment]
@yEinFallsLos please test on Windows

**Comment by aydreas** [comment]
@Liioooo works fine on windows 👍
Only default profile picture doesn't load

**Comment by Liioooo** [comment]
TODO: deployment via Github Actions

**Comment by Liioooo** [comment]
TODO: update Download Page release Api Url
