### ISSUE TITLE
Also save component if directly opened (eg. without a project)

### ISSUE THREAD

**Issue by aydreas** [logigator/logigator#44]

**Comment by Liioooo** [comment]
Save Component on Save, but Save as popup is displayed nonetheless.

**Comment by aydreas** [comment]
@Liioooo Can we easily check if the main project has been touched?

**Comment by Liioooo** [comment]
@yEinFallsLos Yes we can. The project has an property `saveDirty`. The only downside of this would be that you wouldn't be able to save empty projects form the editor anymore. But this is compromise we can make in my opinion.

**Comment by aydreas** [comment]
Yeah I don't think that's much of a concern.
