### ISSUE TITLE
Login Screen shows 'old' Twitter/X name

### ISSUE THREAD

**Issue by AndreasWeichselbaum** [logigator/logigator#73]
### Description

The redirects to  'Twitter' login: https://logigator.com/login
**It's called 'X' now!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!111**

**Comment by aydreas** [comment]
Twitter login got removed, so this is not relevant anymore. :)
